openapi: 3.0.2
info:
  title: 'CostsMap API'
  version: '2.0.0'
paths:
  /accounts/user/:
      get:
          operationId: concreteUser
          description: Current user information
          parameters: []
          responses:
              '200':
                  content:
                      application/json:
                          schema:
                              type: object
                              properties:
                                  pk:
                                      type: string
                                      example: "c840ad15-0760-4e05-b510-31c71d49da3b"
                                      maxLength: 36
                                      minLength: 36
                                  username:
                                      type: string
                                      example: "username"
                                  email:
                                      type: string
                                      example: "example@email.com"
                  description: ''
          tags:
          - accounts
  /accounts/signup/:
      post:
          operationId: signup
          description: Signup a new user
          parameters: []
          requestBody:
              content:
                  application/json:
                      schema:
                          type: object
                          items: []
                          example:
                              email: "example@gmail.com"
                              password1: "password"
                              password2: "password"
          responses:
              '201':
                  content:
                      application/json:
                          schema:
                              type: object
                              properties:
                                  key:
                                      type: string
                                      example: "5a8d2d2cd57448c27ac75543adbd5d7ba7149ec0"
                  description: ''
          tags:
          - accounts
  /accounts/login/:
      post:
          operationId: login
          description: Login an existing user
          parameters: []
          requestBody:
              content:
                  application/json:
                      schema:
                          type: object
                          items: []
                          example:
                              email: "example@gmail.com"
                              password: "password"
          responses:
              '200':
                  content:
                      application/json:
                          schema:
                              type: object
                              properties:
                                  key:
                                      type: string
                                      example: "5a8d2d2cd57448c27ac75543adbd5d7ba7149ec0"
                  description: ''
          tags:
          - accounts
  /accounts/logout/:
      post:
          operationId: logout
          description: Logout from current account
          parameters: []
          responses:
              '200':
                  content:
                      application/json:
                          schema:
                              type: object
                              properties:
                                  detail:
                                      type: string
                                      example: "Successfully logged out."
                  description: ''
          tags:
          - accounts
  /costs/:
    get:
      operationId: listAllCosts
      description: Return all user costs list
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCosts'
          description: ''
      tags:
      - costs
    post:
        operationId: createCost
        description: Create a new cost for user
        parameters: []
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        items: []
                        example:
                            title: "New Cost"
                            costs_sum: 100.0
                            category: "c71caa23-909d-4ec7-90ab-aecc15f6a6f9"
        responses:
            '201':
                content:
                    application/json:
                        type: object
                        items: []
                        example:
                            cost: "df3f5157-d219-4844-98d4-9ea708dd6f7d"
        tags:
        - costs
  /costs/{cost_id}/:
      get:
          operationId: concreteCost
          description: Return a concrete cost using id
          parameters:
              - name: cost_id
                in: path
                required: true
                description: "UUID of cost"
                schema:
                    type: string
          responses:
              '200':
                  content:
                      application/json:
                          schema:
                              $ref: '#/components/schemas/Cost'
                  description: ''
          tags:
          - costs
      put:
          operationId: updateCost
          description: Update the existing cost
          parameters:
              - name: cost_id
                in: path
                required: true
                description: "UUID of updating cost"
                schema:
                    type: string
          requestBody:
              content:
                  application/json:
                      schema:
                          type: object
                          items: []
                          example:
                              title: "Changing Cost"
                              costs_sum: 100.0
                              category: "c71caa23-909d-4ec7-90ab-aecc15f6a6f9"
          responses:
              '204':
                  description: 'The cost was changed successfully'
          tags:
          - costs
      delete:
          operationId: deleteCost
          description: Delete the existing cost
          parameters:
              - name: cost_id
                in: path
                required: true
                description: "UUID of deleting cost"
                schema:
                    type: string
          responses:
              '204':
                  description: 'The cost was deleted successfully'
          tags:
          - costs
  /costs/{year}/{month}/:
    get:
      operationId: listMonthCosts
      description: Return user costs for the month
      parameters:
        - name: year
          in: path
          required: true
          description: "year of cost date"
          schema:
            type: string
        - name: month
          in: path
          required: true
          description: "month of cost date"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCosts'
          description: ''
      tags:
      - costs
  /costs/{year}/{month}/{day}/:
    get:
      operationId: listDayCosts
      description: Return user costs for the concrete day
      parameters:
        - name: year
          in: path
          required: true
          description: "year of cost date"
          schema:
            type: string
        - name: month
          in: path
          required: true
          description: "month of cost date"
          schema:
            type: string
        - name: day
          in: path
          required: true
          description: "day of cost date"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCosts'
          description: ''
      tags:
      - costs
  /costs/statistic/{year}/{month}/:
    get:
      operationId: statisticMonthCosts
      description: Statistic of costs for the month
      parameters:
        - name: year
          in: path
          required: true
          description: "year of cost date"
          schema:
            type: string
        - name: month
          in: path
          required: true
          description: "month of cost date"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                  type: array
                  items:
                      type: object
                      properties:
                          category:
                              type: string
                              minLength: 1
                              maxLength: 255
                              example: "Food"
                          costs:
                              type: number
                              format: float
                              example: 100.0
          description: ''
      tags:
      - costs
  /costs/statistic/{year}/:
    get:
      operationId: statisticYearCosts
      description: Statistic of costs for the year
      parameters:
        - name: year
          in: path
          required: true
          description: "year of cost date"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                  type: array
                  items:
                      type: object
                      properties:
                          cost_month:
                              type: number
                              format: float
                              example: 5.0
                          cost_sum:
                              type: number
                              format: float
                              example: 100.0
          description: ''
      tags:
      - costs
  /costs/statistic/average/:
    get:
      operationId: statisticAverageCosts
      description: Average costs for the day
      responses:
        '200':
          content:
            application/json:
              schema:
                  type: object
                  properties:
                      average_costs:
                          type: number
                          format: float
                          example: 100
          description: ''
      tags:
      - costs
  /incomes/:
    get:
      operationId: listAllIncomes
      description: Return all user incomes list
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIncomes'
          description: ''
      tags:
      - incomes
    post:
        operationId: createIncome
        description: Create a new income for user
        parameters: []
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        items: []
                        example:
                            incomes_sum: 100.0
        responses:
            '201':
                content:
                    application/json:
                        type: object
                        items: []
                        example:
                            income: "df3f5157-d219-4844-98d4-9ea708dd6f7d"
        tags:
        - incomes
  /incomes/{income_id}/:
      get:
          operationId: concreteIncome
          description: Return a concrete income using id
          parameters:
              - name: income_id
                in: path
                required: true
                description: "UUID of income"
                schema:
                    type: string
          responses:
              '200':
                  content:
                      application/json:
                          schema:
                              $ref: '#/components/schemas/Income'
                  description: ''
          tags:
          - incomes
      put:
          operationId: updateIncome
          description: Update the existing income
          parameters:
              - name: income_id
                in: path
                required: true
                description: "UUID of updating income"
                schema:
                    type: string
          requestBody:
              content:
                  application/json:
                      schema:
                          type: object
                          items: []
                          example:
                              incomes_sum: 100.0
          responses:
              '204':
                  description: 'The income was changed successfully'
          tags:
          - incomes
      delete:
          operationId: deleteIncome
          description: Delete the existing income
          parameters:
              - name: income_id
                in: path
                required: true
                description: "UUID of deleting income"
                schema:
                    type: string
          responses:
              '204':
                  description: 'The income was deleted successfully'
          tags:
          - incomes
  /incomes/{year}/{month}/:
    get:
      operationId: listMonthIncomes
      description: Return user incomes for the month
      parameters:
        - name: year
          in: path
          required: true
          description: "year of income date"
          schema:
            type: string
        - name: month
          in: path
          required: true
          description: "month of income date"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIncomes'
          description: ''
      tags:
      - incomes
  /incomes/{year}/{month}/{day}/:
    get:
      operationId: listDayIncomes
      description: Return user incomes for the concrete day
      parameters:
        - name: year
          in: path
          required: true
          description: "year of income date"
          schema:
            type: string
        - name: month
          in: path
          required: true
          description: "month of income date"
          schema:
            type: string
        - name: day
          in: path
          required: true
          description: "day of income date"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIncomes'
          description: ''
      tags:
      - incomes
  /categories/:
    get:
      operationId: listAllCategories
      description: Return all user categories list
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCategories'
          description: ''
      tags:
      - categories
    post:
        operationId: createCategory
        description: Create a new category for user
        parameters: []
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        items: []
                        example:
                            title: "New Category"
        responses:
            '201':
                content:
                    application/json:
                        type: object
                        items: []
                        example:
                            category: "df3f5157-d219-4844-98d4-9ea708dd6f7d"
        tags:
        - categories
  /categories/{category_id}/:
      get:
          operationId: concreteCategory
          description: Return a concrete category using id
          parameters:
              - name: category_id
                in: path
                required: true
                description: "UUID of category"
                schema:
                    type: string
          responses:
              '200':
                  content:
                      application/json:
                          schema:
                              $ref: '#/components/schemas/Category'
                  description: ''
          tags:
          - categories
      put:
          operationId: updateCategory
          description: Update the existing category
          parameters:
              - name: category_id
                in: path
                required: true
                description: "UUID of updating category"
                schema:
                    type: string
          requestBody:
              content:
                  application/json:
                      schema:
                          type: object
                          items: []
                          example:
                              title: "Changing Category"
          responses:
              '204':
                  description: 'The income was changed successfully'
          tags:
          - categories
      delete:
          operationId: deleteCategory
          description: Delete the existing category
          parameters:
              - name: category_id
                in: path
                required: true
                description: "UUID of deleting category"
                schema:
                    type: string
          responses:
              '204':
                  description: 'The category was deleted successfully'
          tags:
          - categories
  /categories/{category_id}/costs/:
    get:
      operationId: listCategoryCosts
      description: Return user costs in category
      parameters:
          - name: category_id
            in: path
            required: true
            description: "UUID of category"
            schema:
                type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                    category:
                        type: string
                        example: Some Category
                        minLength: 1
                        maxLength: 255
                    total_sum:
                        type: number
                        format: float
                        example: 100.0
                    costs:
                        type: array
                        items:
                            $ref: '#/components/schemas/Cost'
          description: ''
      tags:
      - categories
components:
    schemas:
        Cost:
            type: object
            properties:
                pk:
                    type: string
                    example: "c840ad15-0760-4e05-b510-31c71d49da3b"
                    maxLength: 36
                    minLength: 36
                title:
                    type: string
                    example: Some cost
                    maxLength: 255
                    minLength: 1
                costs_sum:
                    type: number
                    format: float
                    example: 100.0
                category:
                    type: string
                    example: "20cd8674-943f-443e-a60b-b7fe4b1f51ea"
                    maxLength: 36
                    minLength: 36
                owner:
                    type: integer
                    format: int32
                    example: 1
                date:
                    type: string
                    format: date
        ListCosts:
            type: object
            properties:
                total_sum:
                    type: number
                    format: float
                    example: 100.0
                costs:
                    type: array
                    items:
                        $ref: '#/components/schemas/Cost'
        Income:
            type: object
            properties:
                pk:
                    type: string
                    example: "c840ad15-0760-4e05-b510-31c71d49da3b"
                    maxLength: 36
                    minLength: 36
                incomes_sum:
                    type: number
                    format: float
                    example: 100.0
                owner:
                    type: integer
                    format: int32
                    example: 1
                date:
                    type: string
                    format: date
        ListIncomes:
            type: object
            properties:
                total_sum:
                    type: number
                    format: float
                    example: 100.0
                incomes:
                    type: array
                    items:
                        $ref: '#/components/schemas/Income'
        Category:
            type: object
            properties:
                pk:
                    type: string
                    example: "c840ad15-0760-4e05-b510-31c71d49da3b"
                    maxLength: 36
                    minLength: 36
                title:
                    type: string
                    example: Some category
                    maxLength: 255
                    minLength: 1
                owner:
                    type: integer
                    format: int32
                    example: 1
        ListCategories:
            type: array
            items:
                $ref: '#/components/schemas/Category'
